### PR TITLE
Adding more options for Single Table Inheritance in Doctrine 2 Annotation

### PR DESCRIPTION
**Pull request by molaux**
Hello,
here is my attempt to make Single Inheritance more customizable.
I had to make possible to force generation of array keys in MwbExporter/Object/Annotation.php in order to be able to specify integer discrimanator values. When defining php array keys as string representation of integer, php interprets those as integer, then Annotation::isKeysNumeric is not suficient to determine wether or not to write these keys. In this case (and when discriminator is an integer), discriminatorMap Annotation was not able to write keys, as specified by user. Not sure it was the best way to achieve this.

### CODE REVIEW

**Comment by molaux** [comment]
After further reading, I'm figuring out that it may be possible to make it entirely though single table inheritance (it seems I misunderstood the «SINGLE» word in thinking that hierarchy tree could only have a unique parent entity) : 

BasePerson (@Entity, @InheritanceType("SINGLE_TABLE"), @DiscriminatorMap({"base_person" = "BasePerson", "person" = "Person", "base_man" = "BaseMan", "man" = "Man", "base_woman" = "BaseWoman", "woman" = "Woman"}))
Person extends BasePerson (@Entity)
BaseMan extends Person (@Entity) - BaseWoman extends Person (@Entity)
Man extends BaseMan (@Entity) - Woman extends BaseWoman (@Entity)

Maybe it should be more suitable and simple ?

**Comment by malutanpetronel** [comment]
how the annotation in the comment table should look in the BasePerson in order to obtain the 
BasePerson (@Entity, @InheritanceType("SINGLE_TABLE"), @DiscriminatorMap({"base_person" = "BasePerson", "person" = "Person", "base_man" = "BaseMan", "man" = "Man", "base_woman" = "BaseWoman", "woman" = "Woman"})) ? Can you please share it ?

**Comment by molaux** [comment]
6 months later, I commited and rebased my enhancements to handle single inheritance while benefits from "base" classes. I added in the same time some functionalities I was needing while developping and testing.
See example/data/inheritance.mwb for the example. The extraction of resulting code can be found on a branch of mine (https://github.com/molaux/mysql-workbench-schema-exporter/blob/test-inheritance/test) in the test folder. Have a look at the config file mwb-exporter.test.json
Notes :
  * I had to make directories more customizable and so added the possibility to manage different directories for Entities, Ropositories and BaseEntities. For that purpose, the "dir" main config points now to the target bundle base directory (instead of entities one) : subdirectories for Entities, Ropositories and BaseEntities are now deduced from subnamespaces in configuration (entityNamespace, repositoryNamespace and baseEntityNamespace). With a lot of tables, it's much comfortable.
  * I also made base classes abstract as they should not exist in database. In the same idea, it's not referenced in discriminator map as 'base' anymore
  * I added few configuration options like overwriteExtendedEntities or generateSingleInheritance (this one generates a singleton discrimanator map even if there is no discriminator map in table comment and no extendable entity is configured) that are not yet documented
  * the default main entity discriminator is "extended" (to stay backward compatible) if not supplied through comment and if discriminator type is string
  * getters and setters involves now BaseEntities whereas doctrine annotations (relations, etc...) use leaves (Entities)
  * I did my best to follow conventions. Tell me if I'm still wrong.

To do:
  * Abstract "base" classes being not referenced in discriminator map anymore, it should be checked if single inheritance is still needed to achieve extendableEntities mode when no single inheritance is expected;
  * in my example, I tested adding getters and setters to Violonist and Violon child entity to see if it works as expected. In a next session I plan to generate it directly in Violonist and Violon base class by simply configuring foreign key comment in MWB;
  * at present time, single inheritance generates only a one level deep tree where leaves are all descedent from main entity. It would be great to be able to describe a more complexe tree through the table dicriminator comment; It is not a very hard work.

**Comment by molaux** [comment]
@malutanpetronel, sorry to answer your question so late but I had to finish this before, and so much other things even before. Have a look at my example (particularly, the comments on Tools, Persons, and Skills) and the README.md file.

**Comment by malutanpetronel** [comment]
thx... no hurry :) anytime an answer is good ;)

**Comment by molaux** [comment]
The recent project refactor makes my pull request obsolete. No idea on how to maintain this...

**Pull request closed without merging**
