### PR TITLE
Treat multiple underscores as single ones in underscore table names

### PR DESCRIPTION
**Pull request by DamienHarper**
Treat multiple underscores as single ones in underscore table names when generating Entity names.

Before:
- single_underscore => SingleUnderscore
- multiple__underscores => Multiple_Underscores
- multiple___underscores => Multiple__Underscores

After:
- single_underscore => SingleUnderscore
- multiple__underscores => MultipleUnderscores
- multiple___underscores => MultipleUnderscores

### CODE REVIEW

**Comment by johmue** [comment]
This change looks counterintuitive. I wouldn‘t merge this one.

**Comment by DamienHarper** [comment]
The main reason of this PR is that often, table names contain an underscore because they're composed of several words (eg user_group). An association table name is generally composed of the names of the two relevant tables.
For example: 
- table1: user
- table2: user_group
- association: user_group_user

To get a better readability, I (by convention) double underscores between table names to visually distinguish them when the schema is crowded:
- table1: user
- table2: user_group
- association: user_group__user

In that case, I still want to get fully camelcase entity name (eg UserGroupUser) entity instead of a mix of camelcase and snakecase.

Maybe an additional option (config) could be used to enable/disable this behavior.

**Comment by johmue** [comment]
Your use-case sounds like a very custom and personalized problem. If someone would like to have (needs) underscores the most intentional thing to do would be to chain two underscores. I'm still not convinced it makes sense. Can you probably disable it by default with an option?

**Comment by DamienHarper** [comment]
@johmue could you reconsider this PR please?

**Comment by adrianbardan** [comment]
Well.... unfortunately a lot of other changes have been merged into the doctrine2-exporter project that depend on some of these changes.
Currently the doctrine2-exporter library is not usable.

I've identified 2 problems so far:
- missing the definition of the USERDATATYPE_JSON constant in MwbExporter/Formatter/DatatypeConverterInterface.php
- missing the definition of the method getColumnGetterName() on MwbExporter/Model/Column.php

Let's see if we can at least partially merge some changes to make doctrine2-exporter work.

**Comment by johmue** [comment]
@DamienHarper you should be able to merge this PR now

**Pull request merged**
